default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: localhost
  database: mahesh-roster_development

test:
  <<: *default
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: localhost
  database: mahesh-roster_test

production:
  <<: *default
  database: mahesh-roster_production
  username: mahesh-roster
  password: <%= ENV["MAHESH-ROSTER_DATABASE_PASSWORD"] %>